### ISSUE TITLE
wrong htmlFor label

### ISSUE THREAD

**Issue by vali-um** [AGProjects/sylk-webrtc#12]
Hi,
working with your code i noticed that the htmlFor label in https://github.com/AGProjects/sylk-webrtc/blob/0949caf3faa0284fbacc50cfacd5495626c7b80a/src/app/components/RegisterForm.js#L154 does not match the form field.
I think it should be "inputUser" instead of "inputEmail".
Regards,
Valentin Kleibel

**Comment by tijmenNL** [comment]
@vali-um  You're right. I will correct it.
