### ISSUE TITLE
password field check always evaluates to true

### ISSUE THREAD

**Issue by vali-um** [AGProjects/sylk-webrtc#13]
Hi,
I think i found another small issue.
The password check in https://github.com/AGProjects/sylk-webrtc/blob/36a23a19a93b852cc325dc23897aecb5e3dc760f/src/app/components/RegisterForm.js#L106 alway evaluates true, even if the password field is empty.
One could either use` this.state.password !== ''` or `this.state.password != 0` to check for an empty password.

Regards,
Valentin Kleibel

**Comment by tijmenNL** [comment]
Hi,
Thanks, I checked it and you're correct. In the past we could not rely on the the browser validating the input. Hence we implemented the check like it is. At some point in time this mistake happened.

I will correct it.
