### ISSUE TITLE
make with error

### ISSUE THREAD

**Issue by maximdogonov** [AGProjects/sylk-webrtc#2]
Hi! 

When I build app use make command I get error: 

root@SylkServer:/opt/sylk-webrtc# make
node_modules/.bin/gulp build --type production
[14:18:32] Using gulpfile /opt/sylk-webrtc/gulpfile.js
[14:18:32] Starting 'browserify'...
[14:18:32] Starting 'vendorCSS'...
[14:18:32] Starting 'sass'...
[14:18:32] Starting 'images'...
[14:18:32] Finished 'images' after 656 μs
[14:18:32] Starting 'sounds'...
[14:18:32] Finished 'sounds' after 845 μs
[14:18:32] Starting 'fonts'...
[14:18:32] Finished 'fonts' after 657 μs
[14:18:35] Finished 'vendorCSS' after 3.16 s
[14:18:38] Finished 'sass' after 5.77 s
[14:18:44] gulp-notify: [JS Compile Error] Cannot find module 'react/lib/getEventTarget' from '/opt/sylk-webrtc/node_modules/react-mini-router/lib'
[14:18:44] gulp-notify: [Error running notifier] Could not send message: not found: notify-send
[14:18:44] Finished 'browserify' after 11 s
[14:18:44] Starting 'build'...
[14:18:44] Finished 'build' after 2.12 μs

debian jessy, nodejs v6.9.1, npm 3.10.9

How I can fix that? Thank you!

**Comment by saghul** [comment]
Hi! Just pull again, we just fixed it :-)

**Comment by maximdogonov** [comment]
[14:18:44] gulp-notify: [JS Compile Error] Cannot find module 'react/lib/getEventTarget' from '/opt/sylk-webrtc/node_modules/react-mini-router/lib'  

Problem is same. 
I created new issue #3

**Comment by maximdogonov** [comment]
saghul  your don't fix that and close my ticket? I make pull, and same problem.

**Comment by maximdogonov** [comment]
**root@SylkServer:/opt# git clone https://github.com/AGProjects/sylk-webrtc.git**
Cloning into 'sylk-webrtc'...
remote: Counting objects: 3490, done.
remote: Compressing objects: 100% (94/94), done.
remote: Total 3490 (delta 39), reused 0 (delta 0), pack-reused 3394
Receiving objects: 100% (3490/3490), 3.00 MiB | 5.30 MiB/s, done.
Resolving deltas: 100% (2333/2333), done.
Checking connectivity... done.
root@SylkServer:/opt# cd sylk-webrtc/
root@SylkServer:/opt/sylk-webrtc# ls
app  build  configure  gulp  gulpfile.js  LICENSE  Makefile  package.json  README.md  src  test  TODO
root@SylkServer:/opt/sylk-webrtc# 
root@SylkServer:/opt/sylk-webrtc# chmod a+x configure 
**root@SylkServer:/opt/sylk-webrtc# ./configure**
yarn install v0.16.1
info No lockfile found.
[1/4] Resolving packages...
warning node-uuid@1.4.7: use uuid module instead
warning browser-sync > localtunnel > request > node-uuid@1.4.7: use uuid module instead
warning gulp-server-livereload > vinyl-fs > glob-watcher > gaze > globule > minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
warning gulp-server-livereload > vinyl-fs > glob-watcher > gaze > globule > glob > graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
warning gulp-server-livereload > vinyl-fs > glob-stream > minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
warning browser-sync > localtunnel > request > tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
warning electron-builder > progress-stream > through2 > xtend > object-keys@0.4.0: 
[2/4] Fetching packages...
warning fsevents@1.0.15: The platform "linux" is incompatible with this module.
info "fsevents@1.0.15" is an optional dependency and failed compatibility check. Excluding it from installation.
warning 7zip-bin-win@2.0.2: The platform "linux" is incompatible with this module.
info "7zip-bin-win@2.0.2" is an optional dependency and failed compatibility check. Excluding it from installation.
warning 7zip-bin-mac@1.0.1: The platform "linux" is incompatible with this module.
info "7zip-bin-mac@1.0.1" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning Unmet peer dependency "angular@< 2".
warning Unmet peer dependency "jquery@>= 1.7".
[4/4] Building fresh packages...
success Saved lockfile.
$ install-app-deps
Installing app dependencies for arch x64 to /opt/sylk-webrtc/app

Done in 58.76s.
**root@SylkServer:/opt/sylk-webrtc# make** 
node_modules/.bin/gulp build --type production
[05:36:09] Using gulpfile /opt/sylk-webrtc/gulpfile.js
[05:36:09] Starting 'browserify'...
[05:36:09] Starting 'vendorCSS'...
[05:36:09] Starting 'sass'...
[05:36:09] Starting 'images'...
[05:36:09] Finished 'images' after 644 μs
[05:36:09] Starting 'sounds'...
[05:36:09] Finished 'sounds' after 836 μs
[05:36:09] Starting 'fonts'...
[05:36:09] Finished 'fonts' after 681 μs
[05:36:12] Finished 'vendorCSS' after 3.14 s
[05:36:15] Finished 'sass' after 5.65 s
**[05:36:22] gulp-notify: [JS Compile Error] Cannot find module 'react/lib/getEventTarget' from '/opt/sylk-webrtc/node_modules/react-mini-router/lib'**
[05:36:22] Finished 'browserify' after 14 s
[05:36:22] Starting 'build'...
[05:36:22] Finished 'build' after 2.02 μs

**Comment by maximdogonov** [comment]
If you want I can give you ssh access?

**Comment by saghul** [comment]
Are you sure you have the latest commits? We now use a fork of react-mini-router which fixes the issue.

Also make sure you are running the latest version of yarn since IIRC there were some issues using GitHub URLs.

**Comment by maximdogonov** [comment]
ok,  

I clone project again, and got same error: 

git clone https://github.com/AGProjects/sylk-webrtc.git
chmod a+x configure 
./configure
make watch

**[04:12:25] Finished 'lint' after 13 s
[04:12:29] gulp-notify: [JS Compile Error] Cannot find module 'react/lib/getEventTarget' from '/opt/sylk-webrtc/node_modules/react-mini-router/lib'
[04:12:29] Finished 'browserify' after 17 s**

after: 
cd /opt/sylk-webrtc/node_modules/react-mini-router
yarn
 **get error: error /opt/sylk-webrtc/node_modules/react-mini-router/node_modules/phantomjs: Command failed.**
npm install -g react@^0.14.8
yarn

cd ../../
make

then without errors. 

Thank you!

**Comment by saghul** [comment]
I still cannot reproduce your failure, sorry.  Do you have yarn installed globally? Can you paste the output of `./configure` ?

> after:
> cd /opt/sylk-webrtc/node_modules/react-mini-router
> yarn
> get error: error /opt/sylk-webrtc/node_modules/react-mini-router/node_modules/phantomjs: Command failed.
> npm install -g react@^0.14.8
> yarn
> 
> cd ../../
> make
> 
> then without errors.

This is incorrect. You now have 2 different versions of react. `./configure` should be enough.

**Comment by maximdogonov** [comment]
root@SylkServer:/opt/sylk-webrtc# ./configure 
yarn install v0.16.1
info No lockfile found.
[1/4] Resolving packages...
warning node-uuid@1.4.7: use uuid module instead
warning browser-sync > localtunnel > request > node-uuid@1.4.7: use uuid module instead
warning gulp > vinyl-fs > glob-stream > minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
warning gulp > vinyl-fs > glob-watcher > gaze > globule > minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
warning gulp > vinyl-fs > glob-watcher > gaze > globule > glob > graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
warning browser-sync > localtunnel > request > tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
warning electron-builder > progress-stream > through2 > xtend > object-keys@0.4.0: 
[2/4] Fetching packages...
warning fsevents@1.0.15: The platform "linux" is incompatible with this module.
info "fsevents@1.0.15" is an optional dependency and failed compatibility check. Excluding it from installation.
warning 7zip-bin-win@2.0.2: The platform "linux" is incompatible with this module.
info "7zip-bin-win@2.0.2" is an optional dependency and failed compatibility check. Excluding it from installation.
warning 7zip-bin-mac@1.0.1: The platform "linux" is incompatible with this module.
info "7zip-bin-mac@1.0.1" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning Unmet peer dependency "angular@< 2".
warning Unmet peer dependency "jquery@>= 1.7".
[4/4] Building fresh packages...
success Saved lockfile.
$ install-app-deps
Installing app dependencies for arch x64 to /opt/sylk-webrtc/app

Done in 69.10s.

**Comment by saghul** [comment]
> yarn install v0.16.1

You need to update yarn to its latest version, as I mentioned here: https://github.com/AGProjects/sylk-webrtc/issues/2#issuecomment-261901718

Or alternatively ditch yarn and use npm directly, but that takes 5x the time :-S
