### ISSUE TITLE
Cannot find module react/lib/getEventTarget  react-mini-router/lib

### ISSUE THREAD

**Issue by maximdogonov** [AGProjects/sylk-webrtc#3]
Problem with make: 

root@SylkServer:/opt/sylk-webrtc# ./configure 
yarn install v0.16.1
info No lockfile found.
[1/4] Resolving packages...
warning node-uuid@1.4.7: use uuid module instead
warning browser-sync > localtunnel > request > node-uuid@1.4.7: use uuid module instead
warning gulp > vinyl-fs > glob-watcher > gaze > globule > minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
warning gulp > vinyl-fs > glob-watcher > gaze > globule > glob > graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
warning gulp > vinyl-fs > glob-stream > minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
warning browser-sync > localtunnel > request > tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
warning electron-builder > progress-stream > through2 > xtend > object-keys@0.4.0: 
[2/4] Fetching packages...
warning fsevents@1.0.15: The platform "linux" is incompatible with this module.
info "fsevents@1.0.15" is an optional dependency and failed compatibility check. Excluding it from installation.
warning 7zip-bin-mac@1.0.1: The platform "linux" is incompatible with this module.
info "7zip-bin-mac@1.0.1" is an optional dependency and failed compatibility check. Excluding it from installation.
warning 7zip-bin-win@2.0.2: The platform "linux" is incompatible with this module.
info "7zip-bin-win@2.0.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning Unmet peer dependency "angular@< 2".
warning Unmet peer dependency "jquery@>= 1.7".
[4/4] Building fresh packages...
success Saved lockfile.
$ install-app-deps
Installing app dependencies for arch x64 to /opt/sylk-webrtc/app

Done in 61.18s.

root@SylkServer:/opt/sylk-webrtc# make
node_modules/.bin/gulp build --type production
[14:08:09] Using gulpfile /opt/sylk-webrtc/gulpfile.js
[14:08:09] Starting 'browserify'...
[14:08:09] Starting 'vendorCSS'...
[14:08:09] Starting 'sass'...
[14:08:09] Starting 'images'...
[14:08:09] Finished 'images' after 661 μs
[14:08:09] Starting 'sounds'...
[14:08:09] Finished 'sounds' after 895 μs
[14:08:09] Starting 'fonts'...
[14:08:09] Finished 'fonts' after 481 μs
[14:08:12] Finished 'vendorCSS' after 3.34 s
[14:08:15] Finished 'sass' after 6.04 s
**[14:08:23] gulp-notify: [JS Compile Error] Cannot find module 'react/lib/getEventTarget' from '/opt/sylk-webrtc/node_modules/react-mini-router/lib'**
[14:08:23] Finished 'browserify' after 14 s
[14:08:23] Starting 'build'...
[14:08:23] Finished 'build' after 2.82 μs
root@SylkServer:/opt/sylk-webrtc# git pull
Already up-to-date.
root@SylkServer:/opt/sylk-webrtc# make
node_modules/.bin/gulp build --type production
[14:09:11] Using gulpfile /opt/sylk-webrt

**Comment by maximdogonov** [comment]
In package.json:
    "react": "^15.1.0",

In node_modules react 15.1.0 no  getEventTarget.

**Comment by maximdogonov** [comment]
git clone https://github.com/AGProjects/sylk-webrtc.git
cd sylk-webrtc/
npm install -g npm
chmod a+x configure 
./configure 
make dist-dev

**Comment by saghul** [comment]
Duplicate of #2
